server:
  port: 8087

spring:
  application:
    name: sender-service

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

rabbitmq:
  # Fila única compartilhada por todos os workers
  queue: pessoa.competing.queue
