server:
  port: 8082

spring:
  application:
    name: consumer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1

rabbitmq:
  exchange: pessoa.fanout
  queue:
    email: pessoa.email-queue
    sms: pessoa.sms-queue
