server:
  port: 8086

spring:
  application:
    name: replier-service

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0

rabbitmq:
  # Mesma fila declarada pelo Requester
  request-queue: pessoa.request.queue
