server:
  port: 8115

spring:
  application:
    name: processor-service

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/idempotent_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  exchange: pagamento.exchange
  routing-key: pagamento.routing-key
  queue: pagamento.queue
