server:
  port: 8097

spring:
  application:
    name: sender-service

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

rabbitmq:
  exchange: pessoa.exchange
  routing-key: pessoa.routing-key
  queue: pessoa.queue
